#!/bin/bash

cd ~/Projets/TI83PCE/Scitools/test/projects

if [ -z "$1" ]
then
      [ -d newTest ] && echo "Folder newTest already exist" && exit
      [ -d newTest/src ] && "Folder newTest/src already exist" && exit
      # [ -d newTest/bin ] && "Folder newTest/bin already exist" && exit
      # [ -d newTest/obj ] && "Folder newTest/obj already exist" && exit
      mkdir newTest
      cd newTest
else
      [ -d $1 ] && echo "Folder $1 already exist" && exit
      [ -d $1/src ] && "Folder $1/src already exist" && exit
      # [ -d $1/bin ] && "Folder $1/bin already exist" && exit
      # [ -d $1/obj ] && "Folder $1/obj already exist" && exit
      mkdir $1
      cd $1
fi

mkdir src

echo "/* Defautl libraries */
#include <graphx.h>
#include <keypadc.h>
#include <fileioc.h>
#include <debug.h>
#include <tice.h>

#include <ti/vars.h>
#include <ti/real.h>

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main()
{
  return 0;
}" >> src/main.cpp

echo "NAME = $1
ICON = 
DESCRIPTION = \"\"
COMPRESSED = NO
ARCHIVED = NO
HAS_PRINTF = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

include \$(shell cedev-config --makefile)" >> makefile

# lite-xl src/main.cpp makefile
