NAME = GENLIST
ICON = icon.png
DESCRIPTION = "Generate lists to derivate for Scitools"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

include $(shell cedev-config --makefile)
